name: Run Validator

on:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час
  workflow_dispatch: # Возможность ручного запуска

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create secrets directory
      run: mkdir -p secrets

    - name: Create service account file
      # Создаем файл ключа из секрета GitHub
      run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > secrets/service_account.json

    - name: Run validator
      env:
        # Передаем ID таблицы через переменную окружения
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        # Если названия листов отличаются от стандартных, их тоже можно добавить сюда:
        # SALES_SHEET: "Продажи 2024"
      run: python -m src.runner
